; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[backup_migrate][version] = "3.x-dev"

projects[ctools][version] = "1.4"

projects[ckeditor][version] = "1.13"

projects[context][version] = "3.2"

projects[date][version] = "2.7"

projects[devel][version] = "1.4"

projects[ds][version] = "2.6"

projects[entity][version] = "1.5"

projects[libraries][version] = "2.2"

projects[link][version] = "1.2"

projects[mailchimp][version] = "2.12"

projects[module_filter][version] = "2.0-alpha2"

projects[references][version] = "2.1"

projects[password_hustle][version] = "1.1"

projects[profile2][version] = "1.3"

projects[views][version] = "3.7"

; Themes
projects[adminimal_theme][version] = "1.3"

projects[omega][version] = "4.2"

projects[shiny][version] = "1.4"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[racv14][download][type] = ""
projects[racv14][download][url] = ""
projects[racv14][type] = "theme"


; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.ui][download][type] = ""
libraries[jquery.ui][download][url] = ""
libraries[jquery.ui][directory_name] = "jquery.ui"
libraries[jquery.ui][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mailchimp][download][type] = ""
libraries[mailchimp][download][url] = ""
libraries[mailchimp][directory_name] = "mailchimp"
libraries[mailchimp][type] = "library"

